### ISSUE TITLE
[FEATURE] Home 화면 확정된 라이팅 반영

### ISSUE THREAD

**Issue by AAminha** [AAminha/kusitms-2nd-exhibition#15]
# ISSUE ✅ : FEATURE

## 📖 DESCRIPTION

Home 페이지에 있는 라이팅이나 그 외 수정사항을 반영합니다.

## ✨ TODO

- [x] 라이팅 수정
  - [x] 캐치프레이즈 섹션
  - [x] 전시 기조 섹션
- [x] 영상 화질 개선
- [x] 반응형 깨지는 포인트 확인
- [x] 푸터 후원/협업사 로고 변경
- [x] API 연결
- [x] 방문록 등록 & 조회 API 연결
- [ ] 플로팅 버튼 링크 수정
- [x] 방문록이 하나도 없는 화면 처리
